### PR TITLE
Allow controller host to be an IPv6 address.

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @rlane

### CODE REVIEW

**Comment by rlane** [comment]
I'd prefer not to raise new exceptions since that throws away the backtrace.

**Comment by kenchiang** [comment]
thanks for taking a look.  pushed new commit.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs22/abat/2015.01.27.2111-m.oftest.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs22/abat/2015.01.27.2111-m.oftest.master/abat.log
/cc

**Pull request closed without merging**
