### PR TITLE
Use a short timeout when polling for packets.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: trivial

### CODE REVIEW

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs22/abat/2015.03.05.0102-m.oftest.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs22/abat/2015.03.05.0102-m.oftest.master/abat.log
/cc

**Comment by rlane** [comment]
What was the reason for this change?

**Comment by wilmo119** [comment]
There are a number of bigtap tests that iterate over all the ports on a switch, send a packet on each port, and expect a packet to be received on the next port. When the oftest polls for the packet it expects to receive, the arrival of the packet seems to be delayed, causing the poll (without timeout) to miss the packet.

**Pull request merged**
